Add greetz favorites and cards test
makostanyan/Home_task pull request #6
Opened 2021-03-23 16:58 UTC by makostanyan

2021-03-23 19:54 UTC, David91 requested changes

2021-03-23 19:54 UTC, David91 commented on src/test/java/greetzTest.java
> +        String expectedName = driver.findElement(By.xpath("//a[@data-id='1142795629']//div[@class='b-products-grid__item-title']")).
Don't use data-id, as it is strongly connected to certain product. Instead select first product or a random one, how you want.

2021-03-23 19:54 UTC, David91 commented on src/test/java/greetzTest.java
> +        driver.findElement(By.xpath("//a[@data-id='1142795629']/..//a/div[@class='b-favourite']")).click();
Same comment for data-id is here.

2021-03-23 19:54 UTC, David91 commented on src/test/java/greetzTest.java
> +        Assert.assertEquals(actualName, expectedName, "Names are the same");
Error message isn't logical. It should contain an assertion error message, if actual and expected names won't be same.

2021-03-23 19:54 UTC, David91 commented on src/test/java/greetzTest.java
> +        String actualName = driver.findElement(By.xpath("//form[@name= 'productAmountForm']/h1")).getText().toLowerCase();
If you make actualName all in lowercases, then it'd be right to make also all letters in lowercase for expectedName.

2021-03-23 19:54 UTC, David91 commented on src/test/java/greetzTest.java
> +        driver.findElement(By.cssSelector("[data-id='3000011108']")).click();
Same comment for data-id.

2021-03-23 19:54 UTC, David91 commented on src/test/java/greetzTest.java
> +        Assert.assertTrue(totalPrice.contains(doublePerPrice), "Total price is correct");
1. This is wrong validation.
Consider price is 3.20. You inserted 3, then price should be 9.60, but somehow it is 19.60.
Your test will pass, because text containing 19.60 contains 9.60 in it.
As a conclusion, prices should have exact match.
2. I thin you misunderstood meaning of message. It displays when assertion fails, so it should have negative content or in short- it should be an error message.

2021-03-23 20:07 UTC, testforham requested changes

2021-03-23 20:07 UTC, testforham commented on src/test/java/greetzTest.java
> +        String actualName = driver.findElement(By.xpath("//form[@name= 'productAmountForm']/h1")).getText().toLowerCase();
What is the need to convert text to lowercase in both `expected` and `actual`'s case then compare?

2021-03-23 20:07 UTC, testforham commented on src/test/java/greetzTest.java
> +        String doublePerPrice = String.valueOf(Double.parseDouble((perPrice.substring(2).replace(",", "."))) * 2);
Unnecessary brackets on 66 and 109

2021-03-24 16:53 UTC, chandranik90 requested changes

2021-03-24 16:53 UTC, chandranik90 commented on src/test/java/GreetzTest.java
> +    WebDriver driver;
Always use `access modifiers` if there is no special reason for not doing it. And prioritize them from narrowest visibility scope the the widest one (from `private` to `public`)

2021-03-24 16:53 UTC, chandranik90 commented on src/test/java/GreetzTest.java
> +        Thread.sleep(30000);
Isn't 30 seconds of sleep too big?

2021-03-24 16:53 UTC, chandranik90 commented on src/test/java/GreetzTest.java
> +        driver.findElement(By.xpath("//i[@data-qa-ref= 'profile-icon']")).click();
`Thread.sleep` should be used between clicks. Otherwise, tests will be flacky.

2021-03-24 16:53 UTC, chandranik90 commented on src/test/java/GreetzTest.java
> +        String actualName = driver.findElement(By.xpath("//form[@name= 'productAmountForm']/h1")).getText().toLowerCase();
Use `title` text or class somehow instead of just `h1` tag. It's not reliable locator

2021-03-24 16:53 UTC, chandranik90 commented on src/test/java/GreetzTest.java
> +        String actualPrice = driver.findElement(By.className("price-normal")).getText().substring(2);
As discussed today, Regular expression can be used here. But it's not a critical issue.

2021-03-24 16:53 UTC, chandranik90 commented on src/test/java/GreetzTest.java
> +        driver.findElement(By.xpath("//div[text() =  'Toegevoegd aan favorieten']")).click();
Not a good idea to rely on the text. Find another way to avoid Dutch texts in locators

2021-03-24 16:53 UTC, chandranik90 commented on src/test/java/GreetzTest.java
> +        Thread.sleep(3000);
Sleep is not needed after find action. There is no any reload or rendering process which should complete after this

2021-03-26 10:37 UTC, merged